### PR TITLE
Add java support

### PR DESCRIPTION
**Pull request by urielsalis**

### CODE REVIEW

**Comment by urielsalis** [comment]
@rohitpaulk any updates?

**Comment by urielsalis** [comment]
Im trying to run 
`docker compose run tester scripts/compile_and_test.sh courses/build-your-own-sqlite java` along with `docker compose run tester scripts/compile_and_test.sh courses/build-your-own-sqlite go` and both fail with 
`  - Executing starter repo script

     /init.sh: exec: line 14: /tester/test.sh: not found

  - Process exited with code 127 (expected: 1)`

**Comment by rohitpaulk** [comment]
> Im trying to run docker compose run tester scripts/compile_and_test.sh courses/build-your-own-sqlite java along with docker compose run tester scripts/compile_and_test.sh courses/build-your-own-sqlite go and both fail with

Yep this usually happens when you run the command outside of the `course-sdk` directory. This is fixed with the new course-sdk version :)

**Comment by rohitpaulk** [comment]
Okay there seem to be some compilation errors with the newer course-sdk here - this it relates to binary files like `.db` being in the repo. Will investigate tomorrow!

**Pull request merged**
